# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Homework_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Homework_2

	pod 'SnapKit'

end

target 'StorageService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StorageService
 
  


end
